// config/default-sprites.js -- Built-in default sprite config.
// Source: Maatlock drawn sprite set

export const defaultSpriteConfig = {
  meta: {
    size: '200px',
    orientation: 'FLAT',
    directory: './assets/sprites-maatlock-drawn_webp/',
    font: './assets/fonts/ariblk.ttf',
    index_font_color_black: [0, 0, 0, 255],
    index_font_color_white: [255, 255, 255, 255],
    index_type: 'key',
    map_algorithm: 'HFGE',
    textbox_font_size: 11,
    textbox_font_color_black: [0, 0, 0, 255],
    textbox_font_color_white: [255, 255, 255, 255],
    textbox_shaped_lines: [106, 120, 130],
    textbox_padding: 0,
    textbox_letter_spacing: 0,
  },

  tiles: {
    P: [
      ['BW-trans_Maatlock_Tile_Grass_1_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass_2_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass_3_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass_4_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass_5_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_1_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_2_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_3_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_4_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_5_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_6_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_7_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_8_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_9_W_FLAT_200px.webp', 0.05],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_10_W_FLAT_200px.webp', 0.05],
    ],
    PD: [
      ['BW-trans_Maatlock_Tile_Grass-Sparse_1_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_2_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_3_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_4_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_5_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_6_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_7_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_8_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_9_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Grass-Sparse_10_W_FLAT_200px.webp', 0.1],
    ],
    PF: [
      ['BW-trans_Maatlock_Tile_Trees-Sparse_1_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_2_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_3_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_4_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_5_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_6_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_7_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_8_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_9_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_10_W_FLAT_200px.webp', 0.1],
    ],
    PS: [
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_1_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_2_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_3_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_4_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_5_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_6_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_7_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_8_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_9_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_10_W_FLAT_200px.webp', 0.1],
    ],
    F: [
      ['BW-trans_Maatlock_Tile_Trees-Dense_1_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_2_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_3_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_4_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_5_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_6_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_7_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_8_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_9_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Dense_10_W_FLAT_200px.webp', 0.035],
      ['BW-trans_Maatlock_Tile_Trees-Med_1_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Trees-Med_2_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Trees-Med_3_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Lake-Trees_1_W_FLAT_200px.webp', 0.02],
      ['BW-trans_Maatlock_Tile_Lake-Trees_2_W_FLAT_200px.webp', 0.02],
      ['BW-trans_Maatlock_Tile_Lake-Trees_3_W_FLAT_200px.webp', 0.01],
    ],
    M: [
      ['BW-trans_Maatlock_Tile_Mountain_1_W_FLAT_200px.webp', 0.33],
      ['BW-trans_Maatlock_Tile_Mountain_2_W_FLAT_200px.webp', 0.33],
      ['BW-trans_Maatlock_Tile_Mountain_3_W_FLAT_200px.webp', 0.34],
    ],
    D: [
      ['BW-trans_Maatlock_Tile_Desert_1_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Desert_2_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Desert_3_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Desert_4_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Desert-Feature_1_W_FLAT_200px.webp', 0.025],
      ['BW-trans_Maatlock_Tile_Desert-Feature_2_W_FLAT_200px.webp', 0.025],
      ['BW-trans_Maatlock_Tile_Desert-Feature_3_W_FLAT_200px.webp', 0.025],
      ['BW-trans_Maatlock_Tile_Desert-Feature_4_W_FLAT_200px.webp', 0.025],
    ],
    S: [
      ['BW-trans_Maatlock_Tile_Swamp_1_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Swamp_2_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Swamp_3_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Swamp_4_W_FLAT_200px.webp', 0.225],
      ['BW-trans_Maatlock_Tile_Lake_1_W_FLAT_200px.webp', 0.025],
      ['BW-trans_Maatlock_Tile_Lake_2_W_FLAT_200px.webp', 0.025],
      ['BW-trans_Maatlock_Tile_Lake_3_W_FLAT_200px.webp', 0.05],
    ],
    H: [
      ['BW-trans_Maatlock_Tile_Hills_1_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_2_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_3_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_4_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_5_W_FLAT_200px.webp', 0.2],
    ],
    HD: [
      ['BW-trans_Maatlock_Tile_Hills_1_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_2_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_3_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_4_W_FLAT_200px.webp', 0.2],
      ['BW-trans_Maatlock_Tile_Hills_5_W_FLAT_200px.webp', 0.2],
    ],
    HF: [
      ['BW-trans_Maatlock_Tile_Trees-Sparse_1_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_2_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_3_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_4_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_5_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_6_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_7_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_8_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_9_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Trees-Sparse_10_W_FLAT_200px.webp', 0.1],
    ],
    HS: [
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_1_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_2_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_3_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_4_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_5_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_6_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_7_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_8_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_9_W_FLAT_200px.webp', 0.1],
      ['BW-trans_Maatlock_Tile_Swamp-Sparse_10_W_FLAT_200px.webp', 0.1],
    ],
  },

  overlay: {
    Risky: [['BW_Maatlock_Overlay_Label-Rating-Risky_1_B_FLAT_200px.webp', 1]],
    Deadly: [['BW_Maatlock_Overlay_Label-Rating-Deadly_1_B_FLAT_200px.webp', 1]],
    Safe: [['BW_Maatlock_Overlay_Label-Rating-Safe_1_B_FLAT_200px.webp', 1]],
    Unsafe: [['BW_Maatlock_Overlay_Label-Rating-Unsafe_1_B_FLAT_200px.webp', 1]],
    'Small tower': [['BW_Maatlock_Overlay_POI-Outpost_1_B_FLAT_200px.webp', 1]],
    'Fortified keep': [['BW_Maatlock_Overlay_POI-Fortress_1_B_FLAT_200px.webp', 1]],
    'Natural landmark': [['BW_Maatlock_Overlay_POI-Outpost_1_B_FLAT_200px.webp', 1]],
    Temple: [['BW_Maatlock_Overlay_POI-Ruins_1_B_FLAT_200px.webp', 1]],
    'Barrow mounds': [['BW_Maatlock_Overlay_POI-Outpost_1_B_FLAT_200px.webp', 1]],
    Village: [['BW_Maatlock_Overlay_POI-City-Med_1_B_FLAT_200px.webp', 1]],
    Town: [['BW_Maatlock_Overlay_POI-Small-POI_1_B_FLAT_200px.webp', 1]],
    'City/metropolis': [
      ['BW_Maatlock_Overlay_POI-City-Large_1_B_FLAT_200px.webp', 0.5],
      ['BW_Maatlock_Overlay_POI-City-Grand_1_B_FLAT_200px.webp', 0.5],
    ],
    Ravine: [['BW_Maatlock_Overlay_POI-Small-POI_1_B_FLAT_200px.webp', 1]],
    'Monster nest': [['BW_Maatlock_Overlay_POI-Dungeon_1_B_FLAT_200px.webp', 1]],
    "Hermit's abode": [['BW_Maatlock_Overlay_POI-Outpost_1_B_FLAT_200px.webp', 1]],
    'Cave formation': [['BW_Maatlock_Overlay_POI-Dungeon_1_B_FLAT_200px.webp', 1]],
    'Ancient dolmens': [['BW_Maatlock_Overlay_POI-Dungeon_1_B_FLAT_200px.webp', 1]],
    'Barbarian camp': [['BW_Maatlock_Overlay_POI-Stronghold_1_B_FLAT_200px.webp', 1]],
    'Holy shrine': [['BW_Maatlock_Overlay_POI-Stronghold_1_B_FLAT_200px.webp', 1]],
    Index: [['BW_Maatlock_Overlay_Note-Empty-Black_1_B_FLAT_200px.webp', 1]],
  },

  palette_poi: {
    Outpost: 'BW_Maatlock_Overlay_POI-Outpost_1_B_FLAT_200px.webp',
    Fortress: 'BW_Maatlock_Overlay_POI-Fortress_1_B_FLAT_200px.webp',
    Ruins: 'BW_Maatlock_Overlay_POI-Ruins_1_B_FLAT_200px.webp',
    'City-Med': 'BW_Maatlock_Overlay_POI-City-Med_1_B_FLAT_200px.webp',
    'Small-POI': 'BW_Maatlock_Overlay_POI-Small-POI_1_B_FLAT_200px.webp',
    'City-Large': 'BW_Maatlock_Overlay_POI-City-Large_1_B_FLAT_200px.webp',
    'City-Grand': 'BW_Maatlock_Overlay_POI-City-Grand_1_B_FLAT_200px.webp',
    Dungeon: 'BW_Maatlock_Overlay_POI-Dungeon_1_B_FLAT_200px.webp',
    Stronghold: 'BW_Maatlock_Overlay_POI-Stronghold_1_B_FLAT_200px.webp',
    'Empty-Black': 'BW_Maatlock_Overlay_Note-Empty-Black_1_B_FLAT_200px.webp',
  },

  palette_meta_one: {
    Safe: 'BW_Maatlock_Overlay_Label-Rating-Safe_1_B_FLAT_200px.webp',
    Unsafe: 'BW_Maatlock_Overlay_Label-Rating-Unsafe_1_B_FLAT_200px.webp',
    Risky: 'BW_Maatlock_Overlay_Label-Rating-Risky_1_B_FLAT_200px.webp',
    Deadly: 'BW_Maatlock_Overlay_Label-Rating-Deadly_1_B_FLAT_200px.webp',
  },

  icons: {
    P: 'BW_Maatlock_Overlay_Icon-Grass_2_B_FLAT_200px.webp',
    PD: 'BW_Maatlock_Overlay_Note-Empty_1_W_FLAT_200px.webp',
    PF: 'BW_Maatlock_Overlay_Icon-Tree-Decid-Black_2_W_FLAT_200px.webp',
    PS: 'BW_Maatlock_Overlay_Icon-Tree-Swamp-Black_1_W_FLAT_200px.webp',
    F: 'BW_Maatlock_Overlay_Icon-Tree-Decid-Black_2_W_FLAT_200px.webp',
    M: 'BW_Maatlock_Overlay_Icon-Mountain-Black_1_W_FLAT_200px.webp',
    D: 'BW_Maatlock_Overlay_Icon-Tree-Desert-Black_1_W_FLAT_200px.webp',
    S: 'BW_Maatlock_Overlay_Icon-Tree-Swamp-Black_1_W_FLAT_200px.webp',
    H: 'BW_Maatlock_Overlay_Icon-Hill-Black_1_W_FLAT_200px.webp',
    HD: 'BW_Maatlock_Overlay_Icon-Hill-Black_1_W_FLAT_200px.webp',
    HF: 'BW_Maatlock_Overlay_Icon-Tree-Decid-Black_2_W_FLAT_200px.webp',
    HS: 'BW_Maatlock_Overlay_Icon-Tree-Swamp-Black_1_W_FLAT_200px.webp',
  },

  ui: {
    select_blue: 'UIPalette_Maatlock_UI_Select-Blue-50trans_1_W_FLAT_200px.webp',
  },

  indexing: {
    index_background_white: 'BW_Maatlock_Overlay_Index-Background_1_W_FLAT_200px.webp',
    index_background_black: 'BW_Maatlock_Overlay_Index-Background_1_B_FLAT_200px.webp',
  },

  textbox: {
    textbox_background_white: 'BW_Maatlock_Overlay_Textbox-Background-White_1_W_FLAT_200px.webp',
    textbox_background_black: 'BW_Maatlock_Overlay_Textbox-Background-Black_1_W_FLAT_200px.webp',
  },

  backfill: {
    backfill_white: 'BW_Maatlock_Tile_Empty_1_W_FLAT_200px.webp',
    backfill_black: 'BW_Maatlock_Tile_Empty_1_B_FLAT_200px.webp',
    backfill_transparent: 'BW_Maatlock_Tile_Empty-Trans_1_W_FLAT_200px.webp',
  },

  palette_terrain: {
    Desert_1: 'BW-trans_Maatlock_Tile_Desert_1_W_FLAT_200px.webp',
    Desert_2: 'BW-trans_Maatlock_Tile_Desert_2_W_FLAT_200px.webp',
    Desert_3: 'BW-trans_Maatlock_Tile_Desert_3_W_FLAT_200px.webp',
    Desert_4: 'BW-trans_Maatlock_Tile_Desert_4_W_FLAT_200px.webp',
    'Desert-Feature_2': 'BW-trans_Maatlock_Tile_Desert-Feature_2_W_FLAT_200px.webp',
    'Desert-Feature_3': 'BW-trans_Maatlock_Tile_Desert-Feature_3_W_FLAT_200px.webp',
    'Desert-Feature_4': 'BW-trans_Maatlock_Tile_Desert-Feature_4_W_FLAT_200px.webp',
    Grass_1: 'BW-trans_Maatlock_Tile_Grass_1_W_FLAT_200px.webp',
    Grass_2: 'BW-trans_Maatlock_Tile_Grass_2_W_FLAT_200px.webp',
    Grass_3: 'BW-trans_Maatlock_Tile_Grass_3_W_FLAT_200px.webp',
    Grass_4: 'BW-trans_Maatlock_Tile_Grass_4_W_FLAT_200px.webp',
    Grass_5: 'BW-trans_Maatlock_Tile_Grass_5_W_FLAT_200px.webp',
    Hills_1: 'BW-trans_Maatlock_Tile_Hills_1_W_FLAT_200px.webp',
    Hills_2: 'BW-trans_Maatlock_Tile_Hills_2_W_FLAT_200px.webp',
    Hills_3: 'BW-trans_Maatlock_Tile_Hills_3_W_FLAT_200px.webp',
    Hills_4: 'BW-trans_Maatlock_Tile_Hills_4_W_FLAT_200px.webp',
    Hills_5: 'BW-trans_Maatlock_Tile_Hills_5_W_FLAT_200px.webp',
    Mountain_1: 'BW-trans_Maatlock_Tile_Mountain_1_W_FLAT_200px.webp',
    Mountain_2: 'BW-trans_Maatlock_Tile_Mountain_2_W_FLAT_200px.webp',
    Mountain_3: 'BW-trans_Maatlock_Tile_Mountain_3_W_FLAT_200px.webp',
    Ocean_1: 'BW-trans_Maatlock_Tile_Ocean_1_W_FLAT_200px.webp',
    Ocean_2: 'BW-trans_Maatlock_Tile_Ocean_2_W_FLAT_200px.webp',
    Ocean_3: 'BW-trans_Maatlock_Tile_Ocean_3_W_FLAT_200px.webp',
    Ocean_4: 'BW-trans_Maatlock_Tile_Ocean_4_W_FLAT_200px.webp',
    Ocean_5: 'BW-trans_Maatlock_Tile_Ocean_5_W_FLAT_200px.webp',
    Swamp_1: 'BW-trans_Maatlock_Tile_Swamp_1_W_FLAT_200px.webp',
    Swamp_2: 'BW-trans_Maatlock_Tile_Swamp_2_W_FLAT_200px.webp',
    Swamp_3: 'BW-trans_Maatlock_Tile_Swamp_3_W_FLAT_200px.webp',
    Swamp_4: 'BW-trans_Maatlock_Tile_Swamp_4_W_FLAT_200px.webp',
  },
};
